"""add transaction_type

Revision ID: rev_1776546734
Revises: 055f52412ff9
Create Date: 2026-04-18 21:12:15.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'rev_1776546734'
down_revision: Union[str, None] = '055f52412ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', sa.String(length=50), server_default='TRANSFER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
